[package]
name = "octyl"
version = "0.1.0"
edition = "2021"

[dependencies]


crossterm = { version = "0.26", features = ["event-stream"] }
ropey = "1.6"
tokio-util = "0.7"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
