[package]
name = "octyl"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "A terminal-based text editor"

[dependencies]

# terminal
crossterm = { version = "0.26", features = ["event-stream"] }
tui = { package = "ratatui", version = "0.22" }

# async
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
futures = "0.3"

# utility
anyhow = "1"

# logging
fern = "0.6"
log = "0.4"
chrono = "0.4"
